name: Bazel Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      go_changes: ${{ steps.changes.outputs.go_changes }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for non-test Go file changes
        id: changes
        run: |
          git fetch origin main --depth=2
          changed=$(git diff --name-only HEAD^ HEAD | grep '\.go$' | grep -v '_test.go' || true)
          if [[ -n "$changed" ]]; then
            echo "go_changes=true" >> $GITHUB_OUTPUT
          else
            echo "go_changes=false" >> $GITHUB_OUTPUT
          fi

  build-and-release:
    if: needs.detect-changes.outputs.go_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: Build binary
        run: |
          bazel build //:starcm
          cp bazel-bin/starcm_/starcm starcm

      - name: Get short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_ENV"
        
      - name: Create GitHub prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.short_sha }}
          name: starcm-${{ env.short_sha }}
          prerelease: true
          files: starcm
