name: Bazel Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: Build binary
        run: |
          bazel build //:starcm
          cp bazel-bin/starcm_/starcm starcm

      - name: Create GitHub prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          name: starcm-${{ github.sha }}
          prerelease: true
          files: starcm
